# Site settings
title: Leandro Fernandes
email: leandroohf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My website to show my pojects and write blog and explore ideas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: leandroohf 
github_username:  leandroohf

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

theme: jekyll-theme-midnight